export interface FishingSpot {
    id: string;
    name: string;
    levelReq: number;
    xpPerTick: number;
    baseTickMs: number;
    successRate: number;
    masteryXp: number;
    items: { id: string; quantity: number }[];
    emoji: string;
    tool: 'net' | 'rod' | 'harpoon' | 'bare_hands';
    areaLabel: string;
}

export const FISHING_SPOTS: FishingSpot[] = [
    {
        id: 'shrimp',
        name: 'Shrimp Spot',
        levelReq: 1,
        xpPerTick: 10,
        baseTickMs: 3000,
        successRate: 1,
        masteryXp: 1,
        items: [{ id: 'raw_shrimp', quantity: 1 }],
        emoji: '🦐',
        tool: 'net',
        areaLabel: 'Coastal Shallows',
    },
    {
        id: 'sardine',
        name: 'Sardine Spot',
        levelReq: 5,
        xpPerTick: 20,
        baseTickMs: 3500,
        successRate: 1,
        masteryXp: 1,
        items: [{ id: 'raw_sardine', quantity: 1 }],
        emoji: '🐟',
        tool: 'rod',
        areaLabel: 'Coastal Shallows',
    },
    {
        id: 'herring',
        name: 'Herring Spot',
        levelReq: 10,
        xpPerTick: 30,
        baseTickMs: 3500,
        successRate: 1,
        masteryXp: 2,
        items: [{ id: 'raw_herring', quantity: 1 }],
        emoji: '🐟',
        tool: 'rod',
        areaLabel: 'Coastal Shallows',
    },
    {
        id: 'trout',
        name: 'Trout Spot',
        levelReq: 20,
        xpPerTick: 50,
        baseTickMs: 4000,
        successRate: 0.95,
        masteryXp: 3,
        items: [{ id: 'raw_trout', quantity: 1 }],
        emoji: '🎣',
        tool: 'rod',
        areaLabel: 'Rivermere Stream',
    },
    {
        id: 'salmon',
        name: 'Salmon Spot',
        levelReq: 30,
        xpPerTick: 70,
        baseTickMs: 5000,
        successRate: 0.9,
        masteryXp: 4,
        items: [{ id: 'raw_salmon', quantity: 1 }],
        emoji: '🐠',
        tool: 'rod',
        areaLabel: 'Rivermere Stream',
    },
    {
        id: 'tuna',
        name: 'Tuna Spot',
        levelReq: 35,
        xpPerTick: 80,
        baseTickMs: 6000,
        successRate: 0.88,
        masteryXp: 5,
        items: [{ id: 'raw_tuna', quantity: 1 }],
        emoji: '🐡',
        tool: 'harpoon',
        areaLabel: 'Deep Gulf',
    },
    {
        id: 'lobster',
        name: 'Lobster Spot',
        levelReq: 40,
        xpPerTick: 90,
        baseTickMs: 7000,
        successRate: 0.85,
        masteryXp: 6,
        items: [{ id: 'raw_lobster', quantity: 1 }],
        emoji: '🦞',
        tool: 'bare_hands',
        areaLabel: 'Deep Gulf',
    },
    {
        id: 'swordfish',
        name: 'Swordfish Spot',
        levelReq: 50,
        xpPerTick: 100,
        baseTickMs: 8000,
        successRate: 0.8,
        masteryXp: 7,
        items: [{ id: 'raw_swordfish', quantity: 1 }],
        emoji: '🐬',
        tool: 'harpoon',
        areaLabel: 'Deep Gulf',
    },
    {
        id: 'shark',
        name: 'Shark Spot',
        levelReq: 76,
        xpPerTick: 110,
        baseTickMs: 10000,
        successRate: 0.7,
        masteryXp: 10,
        items: [{ id: 'raw_shark', quantity: 1 }],
        emoji: '🦈',
        tool: 'harpoon',
        areaLabel: 'Abyssal Waters',
    },
    {
        id: 'cosmic_jellyfish',
        name: 'Cosmic Jellyfish',
        levelReq: 90,
        xpPerTick: 250,
        baseTickMs: 15000,
        successRate: 0.6,
        masteryXp: 15,
        items: [{ id: 'raw_cosmic_jellyfish', quantity: 1 }],
        emoji: '🪼',
        tool: 'bare_hands',
        areaLabel: 'The Void Tide',
    },
];
